---
- name: Prepare network configuration
  block:
  # - replace:
  #     dest: /etc/dhcp/dhclient.conf
  #     regexp: "(,\\s+routers,)"
  #     replace: ","
  #   register: dhclient_conf
  # - shell: "ifdown eth0 ;sleep 1; ifup eth0"
  #   ignore_errors: True
  #   when: dhclient_conf.changed
  - name: Configure default gateway through Public network and route to VIPs
    template: src="999-multirack_lab.j2" dest="/etc/netplan/999-multirack_lab.yaml"
    register: rack_netconfig
  - command: "ip route delete default"
    ignore_errors: True
    when: rack_netconfig.changed
  - shell: "netplan generate && netplan apply"
    # ignore_errors: True
    when: rack_netconfig.changed
