---
- hosts: all
  gather_facts: False
  roles:
    - common

- hosts: masters
  gather_facts: False
  roles:
    - master

- hosts: clients
  gather_facts: False
  roles:
    - client

- hosts: servers
  gather_facts: False
  roles:
    - node
